pipeline {
  agent {
    docker { image 'node:19-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        echo "OllaA comosTas ..!!"
        echo "OllA Senior ..!!"
        sh 'node --version'
      }
    }
  }
}
